#ifndef DOMO_ESP_DEFINES_H
#define DOMO_ESP_DEFINES_H

#define SHUTTER_POWER_THRESHOLD 4.0
#define DEFAULT_SHUTTER_TIMEOUT_MS 30000

#define JUST_ACTIVATED_TIMEOUT 4000

#define DEFAULT_WIFI_SSID "SIFISJOIN"
#define DEFAULT_WIFI_PASSWORD "sifisjoin"

#define DEFAULT_ENERGY_REPORT_INTERVAL 30
#define RITENITIVE_FILE "/rit.json"
#define WIFI_CONFIG_FILE "/wifi.json"
#define HW_CONFIG_FILE "/hw.json"
#define SEC_CONFIG_FILE "/sec.json"


#define INPUT_DEBOUNCE_TIME_MS 75

#define POWER_MEASUREMENT_DEADZONE_W 1.50f
#define ENERGY_MEASUREMENT_DEADZONE_W 1.50f/(2*DEFAULT_ENERGY_REPORT_INTERVAL)

#define FIRMWARE_VERSION "UPDATE_ESP32_SSL";
#endif
